### ISSUE TITLE
CODEOWNERS does not work

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-proto#175]
See #174: No code owners reviews were requested automatically. Maybe something needs to be changed in the repository settings?

**Comment by yurishkuro** [comment]
Settings look ok, may be the owners file itself is an issue

![image](https://user-images.githubusercontent.com/3523016/87982967-9f584c00-caa5-11ea-87ce-490db0cb7c11.png)

**Comment by Oberon00** [comment]
> The people you choose as code owners must have write permissions for the repository. 

Maybe this is the issue?

**Comment by bogdandrutu** [comment]
I fixed that yesterday I think. Can you give a try again?

**Comment by Oberon00** [comment]
I don't currently have a PR open where I could try to push to re-trigger review requests. But at least I still don't see the UI to e.g. label issues, so I guess I don't have write permissions?

**Comment by Oberon00** [comment]
I think once its fixed this https://github.com/open-telemetry/opentelemetry-proto/pull/174#pullrequestreview-451924276 grey "suggest changes" should turn into a red "request changes".

**Comment by bogdandrutu** [comment]
Missed the trace approvers for write access. Fixed
